import type { Product } from './types'

export const products: Product[] = [
  {
    id: '1',
    slug: 'oatmeal-trench',
    name: 'Oatmeal Trench',
    price: 2450,
    material: 'Wool',
    category: 'outerwear',
    description: 'A timeless trench reimagined in undyed oatmeal wool. Cut from a single length of fabric with zero off-cuts, finished by hand in our atelier. Designed to soften with wear and last decades, not seasons.',
    images: [
      '/products/oatmeal-trench.png',
      '/products/oatmeal-trench-2.png',
      '/products/oatmeal-trench-3.png',
      '/products/oatmeal-trench-4.png',
    ],
    is_zero_waste: true,
    in_stock: true,
    status: 'preorder',
    preorder_target: 10,
    preorder_count: 7,
    created_at: '2026-04-01T00:00:00Z',
  },
  {
    id: '2',
    slug: 'refined-column-dress',
    name: 'Refined Column Dress',
    price: 1280,
    material: 'Silk',
    category: 'dresses',
    description: 'A minimalist column silhouette in deadstock silk. Designed to drape, made to last a lifetime. Hand-finished seams, no waste in the cutting room.',
    images: ['/products/refined-column-dress.png'],
    is_zero_waste: true,
    in_stock: true,
    status: 'preorder',
    preorder_target: 10,
    preorder_count: 4,
    created_at: '2026-03-20T00:00:00Z',
  },
  {
    id: '3',
    slug: 'tailored-suit-set',
    name: 'Tailored Suit Set',
    price: 2890,
    material: 'Linen',
    category: 'sets',
    description: 'A two-piece suit cut from a single bolt of certified deadstock linen. Pattern-matched, hand-finished, designed to be worn together or apart.',
    images: ['/products/tailored-suit-set.png'],
    is_zero_waste: true,
    in_stock: true,
    status: 'preorder',
    preorder_target: 10,
    preorder_count: 2,
    created_at: '2026-03-10T00:00:00Z',
  },
  {
    id: '4',
    slug: 'shoes',
    name: 'Hand-stitched Loafers',
    price: 680,
    material: 'Leather',
    category: 'accessories',
    description: 'Hand-stitched loafers from vegetable-tanned leather. Made to be resoled, not replaced. Ages into a patina that\'s entirely yours.',
    images: ['/products/shoes.png'],
    is_zero_waste: false,
    in_stock: true,
    status: 'preorder',
    preorder_target: 10,
    preorder_count: 5,
    created_at: '2026-02-28T00:00:00Z',
  },
]